name: root-signing repository tests with a Sigstore client

on:
  workflow_call:
    inputs:
      metadata_url:
        description: "URL of the sigstore staging TUF repository to test"
        required: true
        type: string

permissions:
  id-token: 'write' # For signing with the GitHub workflow identity

env:
  STAGING_URL: ${{ inputs.metadata_url }}
  IDENTITY: ${{ github.server_url }}/${{ github.repository }}/.github/workflows/custom-test.yml@${{ github.ref }}

jobs:
  cosign:
    runs-on: ubuntu-latest
    steps:
      - uses: sigstore/cosign-installer@59acb6260d9c0ba8f4a2f9d9b48431a222b68e20 # v3.5.0

      - name: Download initial root
        run: curl -o root.json ${STAGING_URL}/10.root.json

      - name: Test published repository with cosign
        run: |
          touch artifact

          # initialize from the published repository
          cosign initialize --root root.json --mirror ${STAGING_URL}

          # sign, then verify using this workflows oidc identity
          cosign sign-blob \
              --yes \
              --bundle bundle.json \
              artifact

          cosign verify-blob \
              --certificate-identity $IDENTITY \
              --certificate-oidc-issuer https://token.actions.githubusercontent.com \
              --bundle bundle.json \
              artifact
