name: TUF-on-CI publish

permissions: {}

on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - id: build-and-upload-repository
        uses: jku/tuf-on-ci/actions/upload-repository@use-delegation-tree-in-build-repository # test bug fix
        with:
          gh_pages: true
          ref: ${{ inputs.ref }}
          metadata_path: './'

  deploy-to-pages:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy TUF-on-CI repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # v4.0.4

  test-deployed-pages:
    needs: deploy-to-pages
    permissions:
      issues: 'write' # for modifying Issues
      id-token: 'write' # for signing with the GitHub Actions workflow identity
    uses: ./.github/workflows/test.yml

  update-issue:
    runs-on: ubuntu-latest
    needs: [build, deploy-to-pages, test-deployed-pages]
    if: always() && !cancelled()
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@a486e2d6fcf93af4cb0f479e6a280f34125647d6 # v0.10.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
