name: TUF-on-CI repository tests

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: '17 4,10,16,22 * * *'

permissions: {}

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set initial root.json for the test
        run: cp metadata/root_history/10.root.json ./root.json

      - name: Smoke test TUF-on-CI repository with a TUF client
        uses: jku/tuf-on-ci/actions/test-repository@fix-test-repo # test bug fix
        with:
          metadata_url: https://jku.github.io/root-signing-test/
          valid_days: 1
          offline_valid_days: 30

  custom-smoke-test:
    permissions:
      id-token: 'write' # For signing with the GitHub workflow identity
    uses: ./.github/workflows/custom-test.yml
    with:
      metadata_url: https://jku.github.io/root-signing-test/

  update-issue:
    runs-on: ubuntu-latest
    needs: [smoke-test, custom-smoke-test]
    # During workflow_call, caller updates issue
    if: always() && !cancelled() && github.workflow == 'TUF-on-CI repository tests'
    permissions:
      issues: 'write' # for modifying Issues
    steps:
      - name: Update the issue for the workflow
        uses: theupdateframework/tuf-on-ci/actions/update-issue@27c49c016591c7cfea57f6b15296f714a5c4a5f6 # v0.13.0
        with:
          token: ${{ secrets.TUF_ON_CI_TOKEN || secrets.GITHUB_TOKEN }}
          success: ${{ !contains(needs.*.result, 'failure') }}
